uuvsimulator/uuv_simulator

README.md
Signed-off-by: Musa Morena Marcusso Manhães (CR/AEI) <musa.marcusso@de.bosch.com>
=> Correcting README.md file. Instructions moved to the Wiki pages.

uuv_descriptions/world_models/ocean/materials/scripts/ocean.material
Signed-off-by: Musa Morena Marcusso Manhães (CR/AEI) <musa.marcusso@de.bosch.com>
=> Setting a more realistic wave amplitude to ocean shader.

uuv_gazebo_plugins/uuv_gazebo_plugins/src/HydrodynamicModel.cc
Signed-off-by: Musa Morena Marcusso Manhães <musa.marcusso@de.bosch.com>
=> Fixing the sign for the added-mass Coriolis coefficients.

uuv_sensor_plugins/uuv_sensor_plugins/src/DvlPlugin.cc, uuv_sensor_plugins/uuv_sensor_plugins/src/RptPlugin.cc, uuv_sensor_plugins/uuv_sensor_plugins/src/SensorPlugin.cc, uuv_sensor_plugins/uuv_sensor_plugins/src/SubseapressurePlugin.cc
warn if no updatePeriod is provided
Signed-off-by: Sebastian Scherer <sebastian.scherer2@de.bosch.com>
=> fix SubseapressurePlugin not obeying updatePeriod,

uuv_gazebo_plugins/uuv_gazebo_plugins/src/HydrodynamicModel.cc
- Consider cross term when computing acceleration wrt body frame.
- Avoid Gazebo's "RelativeAccel" functions due to their ambiguous meaning.
Signed-off-by: Sebastian Scherer <sebastian.scherer2@de.bosch.com>
=> Consider cross term when computing acceleration wrt body frame.

uuv_gazebo_plugins/uuv_gazebo_ros_plugins/src/ThrusterROSPlugin.cc
=> Adding a message to the thruster efficiency method callback functions.

uuv_gazebo_plugins/uuv_gazebo_plugins/src/HydrodynamicModel.cc
Signed-off-by: Sebastian Scherer <Sebastian.Scherer2@de.bosch.com>
=> fix not initialized variable, prevent division by zero

README.md
=> Adding link to Issues page on README.md

uuv_descriptions/models/common/launch/message_to_tf.launch, uuv_descriptions/models/rexrov/launch/upload_rexrov_default.launch, uuv_descriptions/models/rexrov/launch/upload_rexrov_oberon.launch, uuv_descriptions/models/rexrov/launch/upload_rexrov_oberon4.launch, uuv_descriptions/models/rexrov/launch/upload_rexrov_oberon_arms.launch
Signed-off-by: Sebastian Scherer (CR/AEI) <sebastian.scherer2@de.bosch.com>
=> fix message_to_tf, which stopped working for me recently

uuv_descriptions/models/common/launch/message_to_tf.launch
=> Adding the name of the child frame to message_to_tf launch file.

uuv_teleop/uuv_vehicle_teleop/scripts/vehicle_teleop.py
but with different magnitudes
Signed-off-by: Sebastian Scherer (CR/AEI) <sebastian.scherer2@de.bosch.com>
=> vehicle_teleop: use multiple axes for the same direction

uuv_manipulators/uuv_manipulators_commons/uuv_manipulators_control/src/uuv_manipulators_control/cartesian_controller.py
=> FIX Index of the input command vector.

uuv_manipulators/uuv_manipulators_commons/uuv_manipulators_kinematics/CMakeLists.txt, uuv_manipulators/uuv_manipulators_commons/uuv_manipulators_kinematics/src/uuv_manipulator_interfaces/kin_chain.py, uuv_manipulators/uuv_manipulators_commons/uuv_manipulators_kinematics/test/test_kinematic_interfaces.launch, uuv_manipulators/uuv_manipulators_commons/uuv_manipulators_kinematics/test/test_start_simulation.launch
=> FIX Jacobian matrix null output.

uuv_control/uuv_control_utils/CMakeLists.txt
=> ADD send_waypoint_file.py to the install path.

uuv_manipulators/uuv_manipulators_commons/uuv_manipulators_kinematics/src/uuv_manipulator_interfaces/kin_chain.py
=> FIX PyKDL call for Jacobian computation.

uuv_tutorials/uuv_tutorial_rov_model/urdf/rov_example_snippets.xacro
Hopefully fixes  #74 
Signed-off-by: Sebastian Scherer <sebastian.scherer2@de.bosch.com>
=> ADD missing thruster id in tutorials snippets

uuv_gazebo/launch/rexrov_demos/rexrov_default.launch, uuv_gazebo/launch/rexrov_demos/rexrov_default_logitech_joy.launch, uuv_gazebo/launch/rexrov_demos/rexrov_oberon4_demo.launch, uuv_gazebo/launch/rexrov_demos/rexrov_oberon4_demo_logitech_joy.launch, uuv_gazebo/launch/rexrov_demos/rexrov_oberon_arms_demo.launch, uuv_gazebo/launch/rexrov_demos/rexrov_oberon_arms_demo_logitech_joy.launch, uuv_gazebo/launch/rexrov_demos/rexrov_oberon_demo_logitech_joy.launch, uuv_gazebo/launch/rexrov_demos/rexrov_sonar.launch, uuv_gazebo/launch/rexrov_demos/rexrov_sonar_logitech_joy.launch
=> ADD Launch file input for initial yaw in all RexROV demos

uuv_sensor_plugins/uuv_sensor_plugins_ros/urdf/camera_snippets.xacro
Signed-off-by: Luiz Ricardo Douat <luizricardo.douat@de.bosch.com>
=> Add optical frame to camera.

uuv_sensor_plugins/uuv_sensor_plugins_ros/urdf/camera_snippets.xacro
=> FIX Null inertial in the camera optical link

uuv_descriptions/models/rexrov/robots/rexrov_default.xacro, uuv_descriptions/models/rexrov/robots/rexrov_default_noisy_pose.xacro, uuv_descriptions/models/rexrov/robots/rexrov_oberon4.xacro, uuv_descriptions/models/rexrov/robots/rexrov_oberon7.xacro, uuv_descriptions/models/rexrov/robots/rexrov_oberon_arms.xacro, uuv_descriptions/models/rexrov/robots/rexrov_sonar.xacro
=> FIX Joint state publisher update rate

uuv_tutorials/uuv_tutorial_rov_model/launch/upload_rov_example.launch
=> FIX Instance of message_to_tf node in ROV tutorial

uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_base.py
=> ADD Read flag to use stamped poses from parameter server.

uuv_evaluation/scripts/run_smac, uuv_evaluation/scripts/smac_wrapper.py
=> FIX Output cost for crashed simulation iterations.

uuv_sensor_plugins/uuv_sensor_plugins/CMakeLists.txt
wasn't finding opencv header files during build
=> Add OpenCV headers to include dirs and linked libraries

uuv_evaluation/scripts/run_smac, uuv_evaluation/src/parameter_opt/simulation_runner.py
=> FIX Name of the default output folder from the simulation runner wrapper

uuv_control/uuv_thruster_manager/src/uuv_thrusters/thruster_manager.py
=> FIX TF listener timeout before TF frames are updated

uuv_assistants/CMakeLists.txt, uuv_assistants/launch/unpause_simulation.launch, uuv_assistants/scripts/unpause_simulation.py
=> ADD Script and launch file to unpause the simulation

uuv_manipulators/oberon7/oberon7_control/launch/joint_effort_controllers.launch, uuv_manipulators/oberon7/oberon7_description/urdf/parallel_gripper.xacro, uuv_manipulators/oberon7/oberon7_description/urdf/serial_arm.xacro
=> FIX Joint dynamics parameters for Oberon7

uuv_gazebo_plugins/uuv_gazebo_plugins/include/uuv_gazebo_plugins/ThrusterPlugin.hh, uuv_gazebo_plugins/uuv_gazebo_plugins/src/ThrusterPlugin.cc
=> ADD Optional input argument to limit the output thrust force.

uuv_descriptions/models/common/urdf/common.urdf.xacro
=> RM Redundant definition of PI

uuv_control/uuv_trajectory_control/scripts/rov_mb_sm_controller.py, uuv_control/uuv_trajectory_control/scripts/rov_nl_pid_controller.py, uuv_control/uuv_trajectory_control/scripts/rov_nmb_sm_controller.py, uuv_control/uuv_trajectory_control/scripts/rov_pid_controller.py, uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_base.py
The controller could break in case the timer set in the
base class started the update before all parameters were
properly initialized.
=> ADD Flag to check controller initialization

uuv_assistants/templates/robot_model/urdf/gazebo.xacro
=> FIX Set the surface vessel parameters as optional in the template

uuv_assistants/templates/robot_model/urdf/snippets.xacro
=> FIX Comment on thruster macro template xacro file

uuv_evaluation/src/bag_evaluation/evaluation.py, uuv_evaluation/src/bag_evaluation/recording.py, uuv_evaluation/src/parameter_opt/simulation_runner.py
=> FIX Duplicate logging handlers on evaluation scripts

uuv_control/uuv_trajectory_control/scripts/rov_nmb_sm_controller.py
To avoid extreme control efforts from being generated, add an
option to use a saturation function that will fix the chattering
problem with the non-model-based sliding mode controller.
=> FIX Sliding surface with saturation function

uuv_control/uuv_trajectory_control/CMakeLists.txt, uuv_control/uuv_trajectory_control/launch/rov_mb_fl_controller.launch, uuv_control/uuv_trajectory_control/scripts/rov_mb_fl_controller.py
Controller mostly targeted for thruster actuated robot models.
=> ADD Model-based feedback linearization controller

uuv_teleop/launch/finned_uuv_teleop.launch, uuv_teleop/scripts/finned_uuv_teleop.py
=> ADD Joy input gain for thruster command

uuv_gazebo_plugins/uuv_gazebo_ros_plugins/urdf/battery_snippets.xacro, uuv_gazebo_plugins/uuv_gazebo_ros_plugins/urdf/fin_snippets.xacro, uuv_gazebo_plugins/uuv_gazebo_ros_plugins/urdf/misc.xacro, uuv_gazebo_plugins/uuv_gazebo_ros_plugins/urdf/snippets.xacro, uuv_gazebo_plugins/uuv_gazebo_ros_plugins/urdf/thruster_snippets.xacro, uuv_sensor_plugins/uuv_sensor_plugins_ros/urdf/camera_snippets.xacro
=> ADD URDF snippets to Gazebo ROS plugins

uuv_world_plugins/uuv_nc_parser/srv/GetNCData.srv, uuv_world_plugins/uuv_nc_parser/srv/GetNCVariables.srv, uuv_world_plugins/uuv_nc_parser/srv/GetNCVelocity.srv
=> RM shebang line from service configuration files

docs/Makefile
=> FIX make clean for the docs

uuv_assistants/templates/thruster_manager_config/launch/start_thruster_manager.launch.template, uuv_control/uuv_thruster_manager/config/rexrov/thruster_manager.yaml
=> FIX RexROV thruster manager configuration

uuv_assistants/templates/robot_model/robots/default.xacro.template, uuv_assistants/templates/robot_model/urdf/actuators.xacro.template, uuv_assistants/templates/robot_model/urdf/base.xacro.template, uuv_assistants/templates/robot_model/urdf/gazebo.xacro.template, uuv_assistants/templates/robot_model/urdf/sensors.xacro.template, uuv_assistants/templates/robot_model/urdf/snippets.xacro.template
=> RM License headers from URDF template files

uuv_tutorials/uuv_tutorial_seabed_world/worlds/example_underwater.world
=> FIX Seabed underwater world plugin definitions

README.md, docs/source/index.rst, docs/source/refs.bib
=> FIX Bib entry in the documentation

uuv_tutorials/uuv_tutorial_dp_controller/scripts/tutorial_dp_controller.py
=> ADD Init flag to the DP controller tutorial

docs/source/tutorials/config_thruster_manager.rst, docs/source/tutorials/create_new_vehicle.rst
=> FIX Typos on the tutorial docs

uuv_evaluation/src/parameter_opt/simulation_runner.py
=> FIX Type in simulation_runner.py

.gitignore, docs/source/faq.rst, docs/source/installation.rst
Add information on the configuration of the catkin workspace.
=> ADD Information to the FAQ

NOTICE
=> ADD William Baker to the NOTICE file

uuv_sensor_plugins/uuv_sensor_plugins/CMakeLists.txt
=> FIX Build error relating to the new OpenCV 3.3 version update

.gitignore
=> ADD .imdone folder to the gitignore list

.uuv_ci_config/ros_kinetic.sh, .uuv_ci_config/ros_lunar.sh, .uuv_ci_config/run_tests.sh, .uuv_ci_config/uuv_dependencies.sh, uuv_assistants/package.xml
=> ADD Scripts to modularize the build configuration

uuv_control/uuv_thruster_manager/package.xml
Was failing to install on kinetic
Signed-off-by: Will Baker <willcbaker@gmail.com>
=> Add message generation dependency

uuv_control/uuv_control_utils/launch/set_gm_current_perturbation.launch, uuv_control/uuv_control_utils/scripts/set_gm_current_perturbation.py
=> ADD ROS node to set the GM current from launch files

uuv_control/uuv_control_utils/CMakeLists.txt, uuv_control/uuv_control_utils/launch/set_scalar_parameter.launch, uuv_control/uuv_control_utils/scripts/set_scalar_parameter.py
=> ADD Script and launch file to set a scalar parameter using ROS service

3rd-party-licenses.txt, uuv_control/uuv_control_utils/CMakeLists.txt, uuv_control/uuv_thruster_manager/CMakeLists.txt, uuv_evaluation/CMakeLists.txt, uuv_teleop/CMakeLists.txt
=> FIX Catkin requirements for catkin_make and catkin build

uuv_assistants/launch/publish_body_sname.launch
(yaw, pitch, roll) is the convention used by tf
=> FIX Vector for static frame publisher

uuv_control/uuv_control_utils/scripts/send_waypoint_file.py
=> FIX Increase timeout for service init_waypoint_from_file

uuv_control/uuv_trajectory_control/launch/rov_sf_controller.launch, uuv_control/uuv_trajectory_control/scripts/rov_sf_controller.py
=> ADD Option to add vectors as a controller parameter input

uuv_descriptions/worlds/subsea_bop_panel.world
Signed-off-by: Luiz Ricardo Douat <luizricardo.douat@de.bosch.com>
=> FIX: Correct position of subsea panel in the world.

uuv_control/uuv_trajectory_control/launch/rov_pd_grav_compensation_controller.launch, uuv_control/uuv_trajectory_control/scripts/rov_pd_grav_compensation_controller.py
=> ADD PD controller with compensation of restoring forces

uuv_gazebo_plugins/uuv_gazebo_ros_plugins/src/UnderwaterObjectROSPlugin.cc
=> FIX Service name for added-mass offset function

uuv_gazebo_plugins/uuv_gazebo_plugins/src/BuoyantObject.cc
=> FIX Ensure volume is not negative when offset is provided

uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py
=> FIX TF timeout

uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py
=> ADD Input to configure circle path idle radius for AUVs

uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py
=> FIX Turn off smooth approach if Dubins path is being used

uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_base.py, uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py, uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/wp_trajectory_generator.py
=> ADD Robot namespace to log output

uuv_control/uuv_control_utils/scripts/set_gm_current_perturbation.py
=> RM Limits to the input angle limits for GM current

uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py
=> ADD Publish estimated time to target

uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/path_generator/dubins_interpolator.py
=> FIX Computation of max. Z step in Dubins algorithm

uuv_control/uuv_control_cascaded_pids/package.xml
Signed-off-by: Gabriel Arjones <arjones@arjones.com>
=> FIX cascade pid package dependencies

uuv_control/uuv_thruster_manager/src/uuv_thrusters/models/thruster_proportional.py
=> FIX Input for thrust force information for compuation of command value

.uuv_ci_config/uuv_dependencies.sh, uuv_sensor_plugins/uuv_sensor_ros_plugins/CMakeLists.txt
* ADD Sensor plugin libraries to the list of exported libraries
* Fix to issue #293
=> ADD UUV Gazebo ROS libraries to be exported

uuv_gazebo_plugins/uuv_gazebo_ros_plugins/package.xml
Missing a test dependency here, was unable to run tests (isolated)
=> Add uuv_descriptions test depend to uuv_gazebo_ros_plugins

uuv_gazebo_plugins/uuv_gazebo_ros_plugins/package.xml
Reverts uuvsimulator/uuv_simulator#310
=> Revert "Add uuv_descriptions test depend to uuv_gazebo_ros_plugins"

uuv_control/uuv_control_msgs/srv/InitWaypointSet.srv, uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py
Fixed the InitWaypointSet method within dp_controller_planner.py and added interpolator to InitWaypointSet.srv.
=> Fixed the InitWaypointSet method within dp_controller_planner.py

uuv_gazebo_plugins/uuv_gazebo_plugins/src/ThrusterPlugin.cc
=> FIX Access to joint axis and pose for Gazebo 9 API

uuv_simulator/package.xml
=> RM Dependency to uuv_tutorials

uuv_assistants/templates/robot_model/launch/upload.launch.template, uuv_assistants/templates/robot_model/urdf/base.xacro.template, uuv_tutorials/uuv_tutorial_rov_model/launch/upload_rov_example.launch, uuv_tutorials/uuv_tutorial_rov_model/urdf/rov_example_base.xacro
=> Align tutorials and templates to new locations

uuv_assistants/scripts/publish_footprints.py, uuv_assistants/scripts/publish_vehicle_footprint.py, uuv_assistants/scripts/set_simulation_timer.py, uuv_assistants/scripts/unpause_simulation.py, uuv_control/uuv_auv_control_allocator/scripts/control_allocator, uuv_control/uuv_control_cascaded_pids/scripts/AccelerationControl.py, uuv_control/uuv_control_utils/scripts/apply_body_wrench.py, uuv_control/uuv_control_utils/scripts/disturbance_manager.py, uuv_control/uuv_control_utils/scripts/set_gm_current_perturbation.py, uuv_control/uuv_control_utils/scripts/set_thruster_output_efficiency.py, uuv_control/uuv_control_utils/scripts/set_thruster_state.py, uuv_control/uuv_control_utils/scripts/set_timed_current_perturbation.py, uuv_control/uuv_control_utils/scripts/start_circular_trajectory.py, uuv_control/uuv_control_utils/scripts/start_helical_trajectory.py, uuv_control/uuv_control_utils/scripts/trajectory_marker_publisher.py, uuv_control/uuv_thruster_manager/scripts/thruster_allocator.py, uuv_control/uuv_trajectory_control/scripts/demo_wp_trajectory_generator.py, uuv_control/uuv_trajectory_control/scripts/rov_mb_sm_controller.py, uuv_teleop/scripts/finned_uuv_teleop.py, uuv_teleop/scripts/vehicle_teleop.py
Related to issue #268
Signed-off-by: Musa Morena Marcusso Manhães <musa.marcusso@de.bosch.com>
=> Fixing Python 3 compatibility issues for scripts

uuv_control/uuv_control_cascaded_pids/launch/key_board_velocity.launch, uuv_teleop/launch/uuv_keyboard_teleop.launch, uuv_teleop/scripts/vehicle_keyboard_teleop.py
I have had a go at implementing the keyboard teleop control. If it's not quite what you are after, or it needs tweaking please let me know.
Signed-off-by: Tom Oliver Watsham <tom.watsham@outlook.com>
=> FEATURE rov_keyboard_teleop #354

uuv_sensor_plugins/uuv_sensor_ros_plugins/urdf/camera_snippets.xacro
Signed-off-by: Fletcher F Thompson <fletcherthompsonx@gmail.com>
=> Fix to include an optical frame for the underwater camera plugin.

uuv_sensor_plugins/uuv_sensor_ros_plugins/urdf/dvl_snippets.xacro
update_rate. Signed-off-by: Fletcher F Thompson <fletcherthompsonx@gmail.com>
=> Changed dvl_snippets.xacro so that all dvl topics publish at nominated
